### PR TITLE
Fix storyblok-php-richtext-renderer#14

### PR DESCRIPTION
**Pull request by uuf6429**

### CODE REVIEW

**Comment by roberto-butti** [comment]
Thank you, @uuf6429, for this fix.
I have a question for you, could you add a test for this "use case"?
If you don't have time to add the test, feel free to let me know, and i can add it.

**Comment by uuf6429** [comment]
> Thank you, @uuf6429, for this fix. I have a question for you, could you add a test for this "use case"? If you don't have time to add the test, feel free to let me know, and i can add it.

sure thing

**Comment by uuf6429** [comment]
@roberto-butti hey, I added a test, but I just remembered there is another 'bug' that is actually also causing a bad test to succeed.

I will make a separate PR with a fix and explanation... I think it's better than doing it here.

**Comment by rversantos** [comment]
Hey @roberto-butti,  when will this fix be included in a new release?

**Comment by roberto-butti** [comment]
> Hey @roberto-butti, when will this fix be included in a new release?

Hi @rversantos  let me ask to @joaokamun .
From my perspective, the master branch is ready to be released (just pushed the changelog)

**Pull request merged**
